@startuml seq1

box "remote"
participant "LLM API" as api
participant "MCP Server" as mcp
' actually installed on my PC, but still, via IP things
end box

box "local"
boundary "Terminal" as cli

end box

box "main"

box "I/O Loop"
control "Main FSM (Key dist.)" as main
queue "Ext.W Key Pool" as extkey
queue "Int.W Key Pool" as intkey
queue "R Key Pool" as readkey
' internal write, external write, read, are controlled by the key mechanism
end box

box "Agent Loop"
participant "context assembly" as asm
participant "context interceptor" as intrcpt
control "Aliya FSM" as aliya
queue "Exclusive DB tools" as exclusive
participant "context slicer" as slice
database cache
' history is not writable, so there's a rw cache for recent messages
end box

box "Database"
participant config as cfg
collections "history slices" as r.db
collections "prompt slices" as rw.db
database "subsession"
' hisotry is read only, at least before compression
' prompt is no different from history, only to be writable
end box

== scene 1 : load ==

cli --> main : /db load
main --> aliya : INIT
note over aliya : initialization
aliya --> main : INIT - grab readkey
aliya --> aliya : IDLE
cli -> main : uesr message
main --> intkey : grant db write
main --> aliya : DB WORK
aliya --> intkey : get intkey
aliya -> cache : append message

cache -> asm
r.db -> asm
rw.db -> asm

== scene 2 : sub agent in the loop ==

' Main agent have 3 API iterations per loop: 

' 1. TOOL:  tool request, a read-and-forget message only for subagent, declare tool use intention, natural language
' 2. HIDDEN: subconsious, formal output + tool result that is hidden from user, if not in DEBUG
' 3. FORMAL: real message, formal output that is visible for user

' need unique prompt, thats why we broke them down to 3 iterations
' to aviod slow reply, we encourage AI to skip any step as if it wants.
' (to keep context NL clean) TOOL result will be deleted soon, while HIDDEN/FORMAL are preserved

group MAIN TOOL
    cache -> asm
    r.db -> asm
    rw.db -> asm
    asm -> asm : build context for TOOL
    asm -> aliya : context
    aliya <-> api : API request
    aliya -> asm : answer
    asm -> asm : build context for SUB
end

group SUB LOOP
'from MAIN TOOL or SUB NEXT

    aliya -> aliya : SUB LOOP
    subsession -> asm : read
    asm -> aliya : context
    aliya --> main : open subsession if new
    main --> intkey : grant subsession write
    aliya <-> api : API request
    aliya -> intrcpt : read tool requests
    intrcpt <-> mcp : contact MCP server
    intrcpt -> aliya : feedback
    aliya <-> asm : build context
    aliya <-> api : API request
    aliya -> subsession : write
    aliya -> intrcpt : quit SUB check

    alt quit
    intrcpt -> aliya : SUB QUIT
    aliya -> cache : return subagent result (natural language)
    end

    alt next
    intrcpt -> aliya : SUB NEXT
    end    

end

group MAIN HIDDEN
    cache -> asm
    r.db -> asm
    rw.db -> asm
    asm -> asm : build context for HIDDEN
    asm -> aliya : context
    aliya <-> api : API request
    aliya -> cache : append message
    aliya -> aliya : call MAIN FORMAL
end

group MAIN FORMAL
    cache -> asm
    r.db -> asm
    rw.db -> asm
    asm -> asm : build context for FORMAL
    asm -> aliya : context
    aliya <-> api : API request
    aliya -> cache : append message
    aliya -> intrcpt : check if main calls\nfor next loop
    
    alt stop
    aliya -> aliya : call SLICE
    end

    alt next
    aliya -> aliya : call MAIN TOOL
    end
end

group SLICE

    aliya -> main : request r.db append
    mian -> intkey : grant slice append
    cache -> asm
    r.db -> asm
    rw.db -> asm
    asm -> asm : build context for slicer
    asm -> aliya : context
    aliya <-> api : API request
    aliya -> intrcpt : check slice decision

    alt slice
    intrcpt -> slice : job
    slice -> r.db : append slice
    aliya -> cache : clear cache
    end

    alt skip
    aliya --> aliya : do nothing
    end

    aliya --> aliya : call for IDLE
end    


@enduml